"""M6.3 freshness policy fingerprint

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-30 22:48:22.399519

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_quality_reports",
        sa.Column("freshness_policy_jsonb", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "data_quality_reports",
        sa.Column("freshness_policy_fingerprint", sa.String(length=64), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_data_quality_reports_identity"), "data_quality_reports", type_="unique"
    )
    op.create_unique_constraint(
        "uq_data_quality_reports_identity",
        "data_quality_reports",
        [
            "fixture_id",
            "forecast_phase",
            "as_of",
            "schema_version",
            "source_fingerprint",
            "policy_fingerprint",
            "freshness_policy_fingerprint",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_data_quality_reports_identity", "data_quality_reports", type_="unique")
    op.create_unique_constraint(
        "uq_data_quality_reports_identity",
        "data_quality_reports",
        [
            "fixture_id",
            "forecast_phase",
            "as_of",
            "schema_version",
            "source_fingerprint",
            "policy_fingerprint",
        ],
    )
    op.drop_column("data_quality_reports", "freshness_policy_fingerprint")
    op.drop_column("data_quality_reports", "freshness_policy_jsonb")
    # ### end Alembic commands ###
