from __future__ import annotations

from sports_intelligence.db.models.base import Base
from sports_intelligence.db.models.context import (
    DataQualityReport,
    FeatureSnapshot,
    MatchContextRecord,
)
from sports_intelligence.db.models.discovery import (
    Fixture,
    FixtureMetadataSnapshot,
    League,
    ProviderEntityId,
    ProviderObservation,
    RawProviderPayload,
    Season,
    Team,
)
from sports_intelligence.db.models.evaluation import (
    CalibrationBucket,
    CandidateSettlement,
    EvaluationMetric,
    EvaluationRun,
    FixtureResult,
    PredictionSettlement,
)
from sports_intelligence.db.models.jobs import Job, JobAttempt
from sports_intelligence.db.models.predictions import (
    LLMCallAttempt,
    MarketPrediction,
    ModelConfig,
    PredictionRun,
    ProbabilityBaseline,
    PromptVersion,
    RankedCandidate,
)
from sports_intelligence.db.models.snapshots import (
    AvailabilitySnapshot,
    ExternalApiRequest,
    LineupSnapshot,
    OddsEventMapping,
    OddsPrice,
    OddsSnapshotSet,
    QuotaBucket,
    ResearchClaim,
    ResearchDocument,
    ResearchRun,
    StandingSnapshot,
    TeamFormSnapshot,
    TeamStatisticsSnapshot,
)

__all__ = [
    "FixtureResult",
    "PredictionSettlement",
    "CandidateSettlement",
    "EvaluationRun",
    "EvaluationMetric",
    "CalibrationBucket",
    "LLMCallAttempt",
    "MarketPrediction",
    "ModelConfig",
    "PredictionRun",
    "ProbabilityBaseline",
    "PromptVersion",
    "RankedCandidate",
    "AvailabilitySnapshot",
    "Base",
    "DataQualityReport",
    "ExternalApiRequest",
    "FeatureSnapshot",
    "Fixture",
    "FixtureMetadataSnapshot",
    "Job",
    "JobAttempt",
    "League",
    "LineupSnapshot",
    "MatchContextRecord",
    "OddsEventMapping",
    "OddsPrice",
    "OddsSnapshotSet",
    "ProviderEntityId",
    "ProviderObservation",
    "QuotaBucket",
    "RawProviderPayload",
    "ResearchClaim",
    "ResearchDocument",
    "ResearchRun",
    "Season",
    "StandingSnapshot",
    "Team",
    "TeamFormSnapshot",
    "TeamStatisticsSnapshot",
]
